import * as path from 'path';
import { Module } from '@nestjs/common';
import { MailerModule } from '@nestjs-modules/mailer';
import { HandlebarsAdapter } from '@nestjs-modules/mailer/dist/adapters/handlebars.adapter';

@Module({
    imports: [
        MailerModule.forRoot({
            transport: {
                host: 'smtp.mailtrap.io',
                port: 2525,
                auth: {
                    user: '052d2885b47731', //generated by Mailtrap
                    pass: '07518aa25421f9' //generated by Mailtrap
                }
            },
            defaults: {
                from: '"PoProstuWitold" <no-reply@poprostuwitold.com>', // outgoing email ID
            },
            template: {
                dir: path.join(__dirname, 'templates/pages'),
                adapter: new HandlebarsAdapter(),
                options: {
                    strict: true
                }
            },
            options: {
                partials: {
                    dir: path.join(__dirname, 'templates/partials'),
                    options: {
                        strict: true
                    }
                }
            }
        }),
    ]
})
export class MailModule {}