import Head from 'next/head'
import { SocialLogin } from '../components/SocialLogin'
import { SERVER_URL } from '../utils/constants'
import { Container } from '../components/Container'
interface indexProps {

}

const Index: React.FC<indexProps> = ({}) => {
    return (
        <div>
            <Head>
            <title>Nest Next Boilerplate</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            </Head>
            <Container style={{display: 'flex', justifyContent: 'center', margin: 'auto'}}>
                <SocialLogin provider="Google" url={`${SERVER_URL}/auth/google`}/>
                <SocialLogin provider="Facebook" url={`${SERVER_URL}/auth/facebook`}/>
            </Container>
        </div>
    )
}

export default Index