import Head from 'next/head'
import React from 'react'
import { Container } from '../components/Container'
import { useAuthState } from '../context/auth'

interface MeProps {

}

const Me: React.FC<MeProps> = ({}) => {
    const { authenticated, loading, user, provider } = useAuthState()
    return (
        <div>
            <Head>
                <title>My profile</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Container>
            {
                !loading && authenticated && user ?
                <div>
                    <p>id: {user.id}</p>
                    <p>createdAt: {user.createdAt}</p>
                    <p>updatedAt: {user.updatedAt}</p>
                    <p>provider: {user.provider}</p>
                    <p>providerId: {user.providerId}</p>
                    <p>email: {user.email}</p>
                    <p>firstName: {user.firstName}</p>
                    <p>lastName: {user.lastName}</p>
                    <p>displayName: {user.displayName}</p>
                </div> 
                : 'NOT LOGGED'
            }
            </Container>
        </div>
    )
}

export default Me