import React, { FormEvent, useState } from 'react'
import Head from 'next/head'
import { Container } from '../components/Container'
import InputField from '../components/InputField'
import { useAuthDispatch, useAuthState } from '../context/auth'
import { useRouter } from 'next/router'
import axios from 'axios'
import { SocialLogin } from '../components/SocialLogin'
import { SERVER_URL } from '../utils/constants'


interface signInProps {

}

const signIn: React.FC<signInProps> = ({}) => {

    const [email, setEmail] = useState<string>('')
    const [password, setPassword] = useState<string>('')
    const [errors, setErrors] = useState<any>({})
    const dispatch = useAuthDispatch()
    const { authenticated } = useAuthState()

    const router = useRouter()
    if (authenticated) {
        if(router.pathname === '/signup') {
            router.push('/')
        }
        router.back()
    }

    const submitForm = async (event: FormEvent) => {
        event.preventDefault()
    
        try {
            const res = await axios.post('/auth/local/login', {
                email,
                password
            })
            dispatch('LOCAL_LOGIN', res.data.user)
            router.back()
        } catch (err: any) {
            if(err.message.includes(400) || err.message.includes(401)) {
                err.message.includes(400) ? setErrors(err.response.data) : setErrors({message: 'Field is required'})
            }
        }
    }

    return (
        <div>
            <Head>
                <title>Sign in</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Container>
            {/* FORM */}
            <div className="w-96">
            <form onSubmit={submitForm}>
                        <div className="mb-6">
                        </div>
                        <InputField
                            label="Email"
                            type="email"
                            value={email}
                            setValue={setEmail}
                            placeholder="Enter your email"
                            error={errors.message}
                        />
                        <InputField
                            label="Pasword"
                            className="mb-4"
                            type="password"
                            value={password}
                            setValue={setPassword}
                            placeholder="Enter your password"
                            error={errors.message}
                        />
                        <button className="w-full mb-4 btn">
                            Submit
                        </button>
                    </form>
                    <SocialLogin provider="Google" url={`${SERVER_URL}/auth/google`}/>
                    <SocialLogin provider="Facebook" url={`${SERVER_URL}/auth/facebook`}/>
                    </div>
            </Container>
        </div>
    )
}

export default signIn