name: E2e tests

on:
  pull_request:
  push:
    branches: 
      - master
      - dev


jobs:
  test:
    name: Running e2e tests
    runs-on: ubuntu-latest
    env:
      OAUTH_GOOGLE_ID: secret
      OAUTH_GOOGLE_SECRET: secret
      OAUTH_FACEBOOK_ID: secret
      OAUTH_FACEBOOK_SECRET: secret
      JWT_ACCESS_SECRET_KEY: secret
      JWT_ACCESS_EXPIRATION_TIME: 360000
    defaults:
      run:
        working-directory: ./server
    services:
      postgres-tests:
        image: postgres:alpine
        env:
          POSTGRES_USER: tests
          POSTGRES_PASSWORD: tests
          POSTGRES_DB: postgres-tests
        ports:
          - 5431:5432
    steps:
    - uses: actions/checkout@v1
      name: Postgres setup
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install
      run: yarn
    - name: Test
      run: yarn test:e2e
    
